### ISSUE TITLE
Header image blurry

### ISSUE THREAD

**Issue by lukefretwell** [devinsays/wpcom-gather#13]
@devinsays the header image seems blurry. Is there a way to create an alt version for retina displays?

**Comment by devinsays** [comment]
Double the values here: https://github.com/devinsays/wpcom-gather/blob/master/functions.php#L68

**Comment by lukefretwell** [comment]
@devinsays thank you. I uploaded the new code, but now don't see the customization features (nav bg color changes, etc.) in this.
